<a href="https://colab.research.google.com/github/Harika822/projects/blob/master/cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler

In [ ]:
data=pd.read_csv('cancer.csv')
data.head()

id  clump_thickness  size_uniformity  ...  normal_nucleoli  mitoses  class
0  1000025                5                1  ...                1        1      2
1  1002945                5                4  ...                2        1      2
2  1015425                3                1  ...                1        1      2
3  1016277                6                8  ...                7        1      2
4  1017023                4                1  ...                1        1      2

[5 rows x 11 columns]

In [ ]:
data.columns

Index(['id', 'clump_thickness', 'size_uniformity', 'shape_uniformity',
       'marginal_adhesion', 'epithelial_size', 'bare_nucleoli',
       'bland_chromatin', 'normal_nucleoli', 'mitoses', 'class'],
      dtype='object')

In [ ]:
data.drop(['id'],axis=1,inplace=True)
data.head(3)

clump_thickness  size_uniformity  ...  mitoses  class
0                5                1  ...        1      2
1                5                4  ...        1      2
2                3                1  ...        1      2

[3 rows x 10 columns]

In [ ]:
data.describe()

clump_thickness  size_uniformity  ...     mitoses       class
count       699.000000       699.000000  ...  699.000000  699.000000
mean          4.417740         3.134478  ...    1.589413    2.689557
std           2.815741         3.051459  ...    1.715078    0.951273
min           1.000000         1.000000  ...    1.000000    2.000000
25%           2.000000         1.000000  ...    1.000000    2.000000
50%           4.000000         1.000000  ...    1.000000    2.000000
75%           6.000000         5.000000  ...    1.000000    4.000000
max          10.000000        10.000000  ...   10.000000    4.000000

[8 rows x 9 columns]

In [ ]:
#replacing the missing values with zero
data.replace('?',0,inplace=True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 10 columns):
clump_thickness      699 non-null int64
size_uniformity      699 non-null int64
shape_uniformity     699 non-null int64
marginal_adhesion    699 non-null int64
epithelial_size      699 non-null int64
bare_nucleoli        699 non-null object
bland_chromatin      699 non-null int64
normal_nucleoli      699 non-null int64
mitoses              699 non-null int64
class                699 non-null int64
dtypes: int64(9), object(1)
memory usage: 54.7+ KB


In [ ]:
data.isnull().sum()

clump_thickness      0
size_uniformity      0
shape_uniformity     0
marginal_adhesion    0
epithelial_size      0
bare_nucleoli        0
bland_chromatin      0
normal_nucleoli      0
mitoses              0
class                0
dtype: int64

In [ ]:
data=data.values

In [ ]:
print(data)

[[5 1 1 ... 1 1 2]
 [5 4 4 ... 2 1 2]
 [3 1 1 ... 1 1 2]
 ...
 [5 10 10 ... 10 2 4]
 [4 8 6 ... 6 1 4]
 [4 8 8 ... 4 1 4]]


In [ ]:
scaler=MinMaxScaler(feature_range=(0,1))
normalizedData=scaler.fit_transform(data)

In [ ]:
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

In [ ]:
x=normalizedData[:,0:9]
y=normalizedData[:,9]

In [ ]:
print("Size of x features" ,x.size)
print("Shape of x features",x.shape)
print("x features byts",x.itemsize)

Size of x features 6291
Shape of x features (699, 9)
x features byts 8
