<a href="https://colab.research.google.com/github/Harika822/projects/blob/master/KNN_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Iris Plants are flowering plants with showy flowers. They are predominantly found in Dry, Semi-desert or colder rocky mountainous areas in Europe and Asia. They have long, Erect flowerin gstems and can produce White, Yellow,Orange,Pink,Purple,Lavender,Blue or Brown colored flowers. They are 260 to 300 ypes of Iris.

> Flowers have 3 Sepals and 3 Petals. The Sepals are usually spreading or drop downwards and petas stand upright partly behind the sepal bases. The Length and width of the sepals and petals vary from each other


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
iris = load_iris()
print(type(iris))
print(iris.keys())

<class 'sklearn.utils.Bunch'>
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [ ]:
print(type(iris.data))

In [ ]:
print(set(iris.target))

{0, 1, 2}


In [ ]:
print(iris.data[::15])

[[5.1 3.5 1.4 0.2]
 [5.7 4.4 1.5 0.4]
 [4.8 3.1 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [5.  2.  3.5 1. ]
 [6.6 3.  4.4 1.4]
 [5.5 2.6 4.4 1.2]
 [7.6 3.  6.6 2.1]
 [6.9 3.2 5.7 2.3]
 [7.7 3.  6.1 2.3]]


In [ ]:
print(iris.target[::15])

[0 0 0 0 1 1 1 2 2 2]


In [ ]:
X = iris.data
y = iris.target

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state =42)
X_train.shape,X_test.shape

((100, 4), (50, 4))

In [ ]:
X_train[:5]

array([[5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ]])

In [ ]:
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train,y_train)
neigh.predict(X_test)
neigh.score(X_test,y_test)

0.98